use 'command -v' instead of 'which'
command is a shell builtin,
which is not installed on all systems.

a missing which command gives the false error:

> ERROR: The following command(s)
> required for building 'kconfig-host'
> are missing on your system: bison, flex